// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NestedAddressFormController from "./nested_address_form_controller"
application.register("nested-address-form", NestedAddressFormController)

import NestedEmailFormController from "./nested_email_form_controller"
application.register("nested-email-form", NestedEmailFormController)